### PR TITLE
[Trey] added embedded font for tandem

### PR DESCRIPTION
**Pull request by colleenpalmer**
https://www.pivotaltracker.com/story/show/30373985

With this fix we should be hosting the font now so there shouldn't be anymore security errors.

### CODE REVIEW

**Comment by treybean** [comment]
Sending back to Colleen because I was getting some 404s and nobody likes a 404 when looking for a font.

**Comment by colleenpalmer** [comment]
Alrighty - I changed the path to be an "asset_url" path now and didn't get any errors anymore. I pulled up a modal box for a creating a new page and it looked like they were pulling in. I also moved them to be in the stylesheets folder too. Let me know if you have any issues...

**Comment by treybean** [comment]
Still not quite working. I looked at the compiled variables.css and it had things like:

``` css
src: url(asset_url "glegoo-regular-webfont.eot?#iefix");
```

which isn't valid css. It looks like you're not using the sass helpers correctly. If you look at the rails guide for the asset pipeline, it will walk you through how you should use them: http://guides.rubyonrails.org/asset_pipeline.html#coding-links-to-assets 2.2.2 talks about css and sass.

Also, I just tried creating a test with putting the fonts in app/assets/fonts/tandem/glegoo-regular-webfont.eot, you can then reference that successfully with:

``` sass
src: asset-url("tandem/glegoo-regular-webfont.eot", font)
```

You can test to make sure it's working by looking at the compiled css and then trying to download the font directly by plugging in the URL into the browser, e.g. http://localhost:3000/assets/tandem/glegoo-regular-webfont.eot

**Comment by colleenpalmer** [comment]
Ok, I read through the docs and switched out those urls. I think I got confused by the src: being there and for some reason was thinking it was pulling in the url alone. anywho... I looked through the css like you suggested and saw that it was pulling in correctly now, and I can hit the url directly and download the font. I don't get why it wouldn't throw up an error for me before though and how it was still pulling in those fonts. I definitely see that it couldn't have been... maybe some weird caching on chrome? weird. 

I did get one warning in the Chrome Inspector, but I'm not sure it effects us. Something to do with the resource being interpreted by 'font' and transferred with MIME...? I looked it up and found an article (http://www.jbarker.com/blog/2011/resource-interpreted-font-transferred-mime-type) that led me to believe it might be something server-side that needs to be set up differently so I'm not sure if that's a problem or not.

**Comment by treybean** [comment]
Merging. yay!

**Comment by colleenpalmer** [comment]
\o/

**Pull request merged**
