### PR TITLE
[Trey, Ethan] Tandem text editor width fix

### PR DESCRIPTION
**Pull request by colleenpalmer**
https://www.pivotaltracker.com/story/show/25883857

Fixed by adding additional classes to form to pull in desired width based on form content

### CODE REVIEW

**Comment by treybean** [comment]
Looks good to me.

**Comment by evizitei** [comment]
I approve, though the merge concerns me as I fear I will not accurately select which styles are correct in the conflicts; perhaps a courtesy merge from master into here?

**Comment by colleenpalmer** [comment]
on it

**Comment by colleenpalmer** [comment]
Ok - I think that should do it. 

I made an additional style change to the new plain text editor box though to make it stretch the width of the colorbox window, so either @treybean or @evizitei if you want to glance over that for a quick check that'd be awesome :)

**Comment by evizitei** [comment]
looks ok to me!

**Pull request merged**
