### PR TITLE
[Trey] History updates

### PR DESCRIPTION
**Pull request by treybean**
https://www.pivotaltracker.com/story/show/25790847

Branched off of non_tandem_page_contents, so merge that first.

### CODE REVIEW

**Comment by colleenpalmer** [comment]
Looks good to me! Do you want @evizitei  to look over the deeper code/dev parts?

**Comment by treybean** [comment]
If he's up for it, otherwise, I think it should be fine.

**Comment by evizitei** [comment]
Go ahead with it, I'm going to zero in on Wolfpack for the afternoon

**Comment by colleenpalmer** [comment]
Ok - going to merge it in.

**Pull request merged**
