### PR TITLE
[Ethan] A few, mostly nav-related, modifications

### PR DESCRIPTION
**Pull request by treybean**

### CODE REVIEW

**Comment by evizitei** [comment]
I have a couple spec failures that are not showing in master; here is the output.

```
Failures:

  1) tandem/pages/edit.html.slim renders the edit page form
     Failure/Error: assert_select "input#page_parent_id", :name => "page[parent_id]"
     MiniTest::Assertion:
       Expected at least 1 element matching "input#page_parent_id", found 0.
     # (eval):2:in `assert'
     # ./spec/views/tandem/pages/edit.html.slim_spec.rb:14:in `block (3 levels) in <module:Tandem>'
     # ./spec/views/tandem/pages/edit.html.slim_spec.rb:13:in `block (2 levels) in <module:Tandem>'

  2) tandem/pages/new.html.slim renders new page form
     Failure/Error: assert_select "input#page_parent_id", :name => "page[parent_id]"
     MiniTest::Assertion:
       Expected at least 1 element matching "input#page_parent_id", found 0.
     # (eval):2:in `assert'
     # ./spec/views/tandem/pages/new.html.slim_spec.rb:14:in `block (3 levels) in <module:Tandem>'
     # ./spec/views/tandem/pages/new.html.slim_spec.rb:13:in `block (2 levels) in <module:Tandem>'
```

**Comment by treybean** [comment]
Hahaha. I saw your comment and was confused because I knew I ran the spec. I went to my terminal to see what was up and saw in the terminal history the exact same failures. I guess it's important to check on the outcome of the tests, not just run 'em. On it.

**Comment by treybean** [comment]
Fixed.

**Comment by evizitei** [comment]
hahahaha, yeah, CI would be a lot easier if we just had to RUN the tests :)

**Pull request merged**
