### PR TITLE
[Colleen] UX Design

### PR DESCRIPTION
**Pull request by colleenpalmer**
- Styled out the page_links navigation and added styles for class .admin-nav so when put on the body tag the page_links will be fixed to the top of the page and push the body down so whole site is visible from the top
- Styled and restructured the new/edit pages for when you add a new page
- Styled out error notifications on modal boxes

New/Edit Pages: https://www.pivotaltracker.com/story/show/24892067
Interface for page_links: https://www.pivotaltracker.com/story/show/24418209, https://www.pivotaltracker.com/story/show/24418279

### CODE REVIEW

**Comment by treybean** [comment]
Reviewed! I'm going to try and get that admin-nav tag in here on this pull request and will send it back for your review and merge here in a bit.

**Comment by colleenpalmer** [comment]
Awesome!

**Comment by treybean** [comment]
Okay, @colleenpalmer take a look. I changed the class for admin-bar to tandem-admin-bar in the same namespacing spirit.

**Comment by colleenpalmer** [comment]
@treybean PERFECT! Works a charm! :)

**Comment by treybean** [comment]
Merge it!

**Pull request merged**
